name: core
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: 3.5.3

# Add regular dependencies here.
dependencies:
  equatable: 2.0.5
  logger: 2.4.0

dev_dependencies:
  lints: 3.0.0
  build_runner: 2.4.13
  flutter_test:
    sdk: flutter
